import Head from "next/head";
import React from "react";
import Link from "next/link";
import Image from "next/image";
import AccountCircle from "@mui/icons-material/AccountCircle";
import LoginIcon from "@mui/icons-material/Login";
import LogoutIcon from "@mui/icons-material/Logout";

import HealthAndSafetyIcon from "@mui/icons-material/HealthAndSafety";
const Layout: React.FC = ({ children }: any) => {
  const [cookiePatient, setCookiePatient] = React.useState<any>("");
  const [cookieDoctor, setCookieDoctor] = React.useState<any>("");

  React.useEffect(() => {
    async function fetchApi() {
      let response = await fetch(`/api/cookie`);
      response = await response
        .json()
        .then((data) => data.cookie.AccessTokenPatient);

      let result = await fetch(`/api/cookie`);
      result = await result.json().then((data) => data.cookie.AccessTokenDoc);

      setCookiePatient(response);
      setCookieDoctor(result);
    }

    fetchApi();
  }, []);

  return (
    <>
      <Head>
        <title>Doctolib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>

      <div className="pos-f-t">
        <div className="collapse" id="navbarToggleExternalContent">
          <div className="bg-primary p-4">
            <h4 className="text-white">Collapsed content</h4>
            <span className="text-muted">Toggleable via the navbar brand.</span>
          </div>
        </div>
        <nav className="navbar navbar-expand-lg navbar-primary bg-primary">
          <div className="container-fluid">
            <Link href="/" passHref={true}>
              {/* <a className="navbar-brand user-select-none">Doctolib</a> */}
              <button className="btn btn-outline-white my-2 my-sm-0">
                <Image
                  src="/logoDoctolib.png"
                  width={120}
                  height={50}
                  alt="logoDoctolib"
                  style={{ borderRadius: "10px" }}
                />
              </button>
            </Link>

            <button
              className="navbar-toggler btn-light"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="nnavbarToggleExternalContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div
              className="collapse navbar-collapse"
              id="navbarSupportedContent"
            ></div>
            <div>
              {cookiePatient === undefined || null ? (
                <div>
                  <Link href="/api/auth/login" passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                    >
                      <a>
                        <LoginIcon />
                        as Patient
                      </a>
                    </button>
                  </Link>
                </div>
              ) : (
                <div>
                  <Link href="/api/auth/logout" passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                    >
                      <a>
                        <LogoutIcon />
                      </a>
                    </button>
                  </Link>
                  <Link href="/PatientProfile" passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                    >
                      <a>
                        {" "}
                        <AccountCircle />
                      </a>
                    </button>
                  </Link>
                </div>
              )}
            </div>
            <div>
              {cookieDoctor === undefined || null ? (
                <div>
                  <Link href="/api/auth/loginDoc" key={"idDoc"} passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                      id="LogDoc"
                    >
                      <a>
                        <HealthAndSafetyIcon />
                      </a>
                    </button>
                  </Link>
                </div>
              ) : (
                <div>
                  <Link href="/DocForm" passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                    >
                      <a>
                        <AccountCircle />
                      </a>
                    </button>
                  </Link>
                  <Link href="/api/auth/logoutDoc" passHref={true}>
                    <button
                      className="btn btn-outline-white my-2 my-sm-0"
                      type="submit"
                    >
                      <a>
                        {" "}
                        <LogoutIcon />
                      </a>
                    </button>
                  </Link>
                </div>
              )}
            </div>
          </div>
        </nav>
        {children}
      </div>
    </>
  );
};
export default Layout;
